const CONFIG = import.meta.env;

export const CHAIN_ID = Number(CONFIG.VITE_CHAIN_ID);
export const CONTRACT_ADDRESS = CONFIG.VITE_CONTRACT_ADDRESS;
export const IMG_LOGO = CONFIG.VITE_IMG_LOGO;
export const EMBEDDED_WALLET_CLIENT = CONFIG.VITE_EMBEDDED_WALLET_CLIENT;
